import type { VariableDefinition } from "@/types/business";

export const EVENT_VARIABLES: VariableDefinition[] = [
  // --- Revenue inputs ---
  {
    id: "eventsPerMonth",
    label: "Events per Month",
    type: "input",
    category: "revenue",
    unit: "count",
    value: 8,
    defaultValue: 8,
    description: "Number of events hosted",
    min: 0,
    step: 1,
  },
  {
    id: "averageTicketPrice",
    label: "Average Ticket/Booking Price",
    type: "input",
    category: "revenue",
    unit: "currency",
    value: 50,
    defaultValue: 50,
    description: "Price per attendee or booking",
    min: 0,
    step: 1,
  },
  {
    id: "averageAttendees",
    label: "Average Attendees/Event",
    type: "input",
    category: "revenue",
    unit: "count",
    value: 100,
    defaultValue: 100,
    description: "Attendees per event",
    min: 0,
    step: 1,
  },

  // --- Cost inputs ---
  {
    id: "venueCostPerEvent",
    label: "Venue Cost/Event",
    type: "input",
    category: "costs",
    unit: "currency",
    value: 500,
    defaultValue: 500,
    description: "Venue rental or direct event space cost",
    min: 0,
    step: 1,
  },
  {
    id: "staffingCostPerEvent",
    label: "Staffing Cost/Event",
    type: "input",
    category: "costs",
    unit: "currency",
    value: 800,
    defaultValue: 800,
    description: "Event staff labor",
    min: 0,
    step: 1,
  },
  {
    id: "suppliesCostPerEvent",
    label: "Supplies Cost/Event",
    type: "input",
    category: "costs",
    unit: "currency",
    value: 300,
    defaultValue: 300,
    description: "Materials, F&B, decor per event",
    min: 0,
    step: 1,
  },
  {
    id: "monthlyMarketingBudget",
    label: "Marketing Budget",
    type: "input",
    category: "costs",
    unit: "currency",
    value: 1000,
    defaultValue: 1000,
    description: "Monthly marketing spend",
    min: 0,
    step: 1,
  },
  {
    id: "monthlyFixedCosts",
    label: "Monthly Fixed Costs",
    type: "input",
    category: "costs",
    unit: "currency",
    value: 3000,
    defaultValue: 3000,
    description: "Rent, insurance, admin, etc.",
    min: 0,
    step: 1,
  },

  // --- Computed ---
  {
    id: "revenuePerEvent",
    label: "Revenue per Event",
    type: "computed",
    category: "revenue",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "averageTicketPrice * averageAttendees",
    dependsOn: ["averageTicketPrice", "averageAttendees"],
    description: "Gross revenue per event",
  },
  {
    id: "monthlyRevenue",
    label: "Monthly Revenue",
    type: "computed",
    category: "revenue",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "revenuePerEvent * eventsPerMonth",
    dependsOn: ["revenuePerEvent", "eventsPerMonth"],
    description: "Total monthly revenue",
  },
  {
    id: "variableCostPerEvent",
    label: "Variable Cost/Event",
    type: "computed",
    category: "costs",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "venueCostPerEvent + staffingCostPerEvent + suppliesCostPerEvent",
    dependsOn: ["venueCostPerEvent", "staffingCostPerEvent", "suppliesCostPerEvent"],
    description: "Direct costs per event",
  },
  {
    id: "totalVariableCosts",
    label: "Total Variable Costs",
    type: "computed",
    category: "costs",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "variableCostPerEvent * eventsPerMonth",
    dependsOn: ["variableCostPerEvent", "eventsPerMonth"],
    description: "All variable costs",
  },
  {
    id: "profitPerEvent",
    label: "Profit per Event",
    type: "computed",
    category: "unitEconomics",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "revenuePerEvent - variableCostPerEvent",
    dependsOn: ["revenuePerEvent", "variableCostPerEvent"],
    description: "Contribution margin per event",
  },
  {
    id: "monthlyCosts",
    label: "Monthly Total Costs",
    type: "computed",
    category: "costs",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "totalVariableCosts + monthlyMarketingBudget + monthlyFixedCosts",
    dependsOn: ["totalVariableCosts", "monthlyMarketingBudget", "monthlyFixedCosts"],
    description: "All costs combined",
  },
  {
    id: "monthlyProfit",
    label: "Monthly Profit",
    type: "computed",
    category: "unitEconomics",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "monthlyRevenue - monthlyCosts",
    dependsOn: ["monthlyRevenue", "monthlyCosts"],
    description: "Net monthly profit",
  },
  {
    id: "profitMargin",
    label: "Profit Margin",
    type: "computed",
    category: "unitEconomics",
    unit: "percent",
    value: 0,
    defaultValue: 0,
    formula: "monthlyRevenue > 0 ? monthlyProfit / monthlyRevenue : 0",
    dependsOn: ["monthlyProfit", "monthlyRevenue"],
    description: "Profit as % of revenue",
  },
  {
    id: "breakEvenEvents",
    label: "Break-Even Events",
    type: "computed",
    category: "unitEconomics",
    unit: "count",
    value: 0,
    defaultValue: 0,
    formula: "profitPerEvent > 0 ? (monthlyMarketingBudget + monthlyFixedCosts) / profitPerEvent : 0",
    dependsOn: ["profitPerEvent", "monthlyMarketingBudget", "monthlyFixedCosts"],
    description: "Events needed to cover fixed costs",
  },
  {
    id: "annualRevenue",
    label: "Annual Revenue",
    type: "computed",
    category: "revenue",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "monthlyRevenue * 12",
    dependsOn: ["monthlyRevenue"],
    description: "Projected annual revenue",
  },
  {
    id: "annualProfit",
    label: "Annual Profit",
    type: "computed",
    category: "unitEconomics",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "monthlyProfit * 12",
    dependsOn: ["monthlyProfit"],
    description: "Projected annual profit",
  },
];
