import type { VariableDefinition } from "@/types/business";

export const MANUFACTURING_VARIABLES: VariableDefinition[] = [
  // --- Revenue inputs ---
  {
    id: "monthlyProductionCapacity",
    label: "Production Capacity/Month",
    type: "input",
    category: "revenue",
    unit: "count",
    value: 10000,
    defaultValue: 10000,
    description: "Maximum units producible",
    min: 0,
    step: 1,
  },
  {
    id: "capacityUtilization",
    label: "Capacity Utilization",
    type: "input",
    category: "revenue",
    unit: "percent",
    value: 0.8,
    defaultValue: 0.8,
    description: "% of capacity actually used",
    min: 0,
    step: 0.01,
  },
  {
    id: "sellingPricePerUnit",
    label: "Selling Price/Unit",
    type: "input",
    category: "revenue",
    unit: "currency",
    value: 25,
    defaultValue: 25,
    description: "Price per unit sold",
    min: 0,
    step: 1,
  },

  // --- Cost inputs ---
  {
    id: "rawMaterialCostPerUnit",
    label: "Raw Material Cost/Unit",
    type: "input",
    category: "costs",
    unit: "currency",
    value: 8,
    defaultValue: 8,
    description: "Material cost per unit",
    min: 0,
    step: 1,
  },
  {
    id: "directLaborCostPerUnit",
    label: "Direct Labor Cost/Unit",
    type: "input",
    category: "costs",
    unit: "currency",
    value: 5,
    defaultValue: 5,
    description: "Labor cost per unit",
    min: 0,
    step: 1,
  },
  {
    id: "overheadCostPerUnit",
    label: "Manufacturing Overhead/Unit",
    type: "input",
    category: "costs",
    unit: "currency",
    value: 3,
    defaultValue: 3,
    description: "Overhead allocated per unit",
    min: 0,
    step: 1,
  },
  {
    id: "yieldRate",
    label: "Yield Rate",
    type: "input",
    category: "operations",
    unit: "percent",
    value: 0.95,
    defaultValue: 0.95,
    description: "% of production meeting quality standards",
    min: 0,
    step: 0.01,
  },
  {
    id: "monthlyFixedCosts",
    label: "Monthly Fixed Costs",
    type: "input",
    category: "costs",
    unit: "currency",
    value: 15000,
    defaultValue: 15000,
    description: "Rent, admin, management, etc.",
    min: 0,
    step: 1,
  },

  // --- Computed ---
  {
    id: "actualProduction",
    label: "Actual Production/Month",
    type: "computed",
    category: "operations",
    unit: "count",
    value: 0,
    defaultValue: 0,
    formula: "monthlyProductionCapacity * capacityUtilization",
    dependsOn: ["monthlyProductionCapacity", "capacityUtilization"],
    description: "Units actually produced",
  },
  {
    id: "qualityUnits",
    label: "Sellable Units/Month",
    type: "computed",
    category: "operations",
    unit: "count",
    value: 0,
    defaultValue: 0,
    formula: "actualProduction * yieldRate",
    dependsOn: ["actualProduction", "yieldRate"],
    description: "Units passing quality control",
  },
  {
    id: "totalMaterialCost",
    label: "Total Material Cost",
    type: "computed",
    category: "costs",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "actualProduction * rawMaterialCostPerUnit",
    dependsOn: ["actualProduction", "rawMaterialCostPerUnit"],
    description: "Monthly raw material spend",
  },
  {
    id: "totalLaborCost",
    label: "Total Direct Labor Cost",
    type: "computed",
    category: "costs",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "actualProduction * directLaborCostPerUnit",
    dependsOn: ["actualProduction", "directLaborCostPerUnit"],
    description: "Monthly direct labor",
  },
  {
    id: "totalManufacturingOverhead",
    label: "Total Manufacturing Overhead",
    type: "computed",
    category: "costs",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "actualProduction * overheadCostPerUnit",
    dependsOn: ["actualProduction", "overheadCostPerUnit"],
    description: "Monthly overhead",
  },
  {
    id: "totalProductionCost",
    label: "Total Production Cost",
    type: "computed",
    category: "costs",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "totalMaterialCost + totalLaborCost + totalManufacturingOverhead",
    dependsOn: ["totalMaterialCost", "totalLaborCost", "totalManufacturingOverhead"],
    description: "All production costs",
  },
  {
    id: "costPerUnit",
    label: "Cost per Sellable Unit",
    type: "computed",
    category: "unitEconomics",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "qualityUnits > 0 ? totalProductionCost / qualityUnits : 0",
    dependsOn: ["totalProductionCost", "qualityUnits"],
    description: "True unit cost (accounts for waste)",
  },
  {
    id: "monthlyRevenue",
    label: "Monthly Revenue",
    type: "computed",
    category: "revenue",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "qualityUnits * sellingPricePerUnit",
    dependsOn: ["qualityUnits", "sellingPricePerUnit"],
    description: "Total monthly revenue",
  },
  {
    id: "grossProfit",
    label: "Gross Profit",
    type: "computed",
    category: "unitEconomics",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "monthlyRevenue - totalProductionCost",
    dependsOn: ["monthlyRevenue", "totalProductionCost"],
    description: "Revenue minus production costs",
  },
  {
    id: "grossMarginPercent",
    label: "Gross Margin %",
    type: "computed",
    category: "unitEconomics",
    unit: "percent",
    value: 0,
    defaultValue: 0,
    formula: "monthlyRevenue > 0 ? grossProfit / monthlyRevenue : 0",
    dependsOn: ["grossProfit", "monthlyRevenue"],
    description: "Production profitability",
  },
  {
    id: "monthlyCosts",
    label: "Monthly Total Costs",
    type: "computed",
    category: "costs",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "totalProductionCost + monthlyFixedCosts",
    dependsOn: ["totalProductionCost", "monthlyFixedCosts"],
    description: "All costs combined",
  },
  {
    id: "monthlyProfit",
    label: "Monthly Profit",
    type: "computed",
    category: "unitEconomics",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "monthlyRevenue - monthlyCosts",
    dependsOn: ["monthlyRevenue", "monthlyCosts"],
    description: "Net monthly profit",
  },
  {
    id: "profitMargin",
    label: "Profit Margin",
    type: "computed",
    category: "unitEconomics",
    unit: "percent",
    value: 0,
    defaultValue: 0,
    formula: "monthlyRevenue > 0 ? monthlyProfit / monthlyRevenue : 0",
    dependsOn: ["monthlyProfit", "monthlyRevenue"],
    description: "Net profit percentage",
  },
  {
    id: "annualRevenue",
    label: "Annual Revenue",
    type: "computed",
    category: "revenue",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "monthlyRevenue * 12",
    dependsOn: ["monthlyRevenue"],
    description: "Projected annual revenue",
  },
  {
    id: "annualProfit",
    label: "Annual Profit",
    type: "computed",
    category: "unitEconomics",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "monthlyProfit * 12",
    dependsOn: ["monthlyProfit"],
    description: "Projected annual profit",
  },
];
