import type { VariableDefinition } from "@/types/business";

export const RESTAURANT_VARIABLES: VariableDefinition[] = [
  // --- Revenue inputs ---
  {
    id: "numberOfSeats",
    label: "Seating Capacity",
    type: "input",
    category: "revenue",
    unit: "count",
    value: 50,
    defaultValue: 50,
    description: "Total seats in the restaurant",
    min: 0,
    step: 1,
  },
  {
    id: "turnsPerDay",
    label: "Table Turns/Day",
    type: "input",
    category: "revenue",
    unit: "count",
    value: 2,
    defaultValue: 2,
    description: "Average seatings per table per day",
    min: 0,
    step: 1,
  },
  {
    id: "averageCheck",
    label: "Average Check",
    type: "input",
    category: "revenue",
    unit: "currency",
    value: 35,
    defaultValue: 35,
    description: "Average spend per customer",
    min: 0,
    step: 1,
  },
  {
    id: "daysOpenPerMonth",
    label: "Days Open/Month",
    type: "input",
    category: "revenue",
    unit: "days",
    value: 26,
    defaultValue: 26,
    description: "Operating days per month",
    min: 0,
    step: 1,
  },

  // --- Cost inputs ---
  {
    id: "foodCostPercent",
    label: "Food Cost %",
    type: "input",
    category: "costs",
    unit: "percent",
    value: 0.3,
    defaultValue: 0.3,
    description: "Food cost as % of revenue (target: 28-35%)",
    min: 0,
    step: 0.01,
  },
  {
    id: "laborCostPercent",
    label: "Labor Cost %",
    type: "input",
    category: "costs",
    unit: "percent",
    value: 0.3,
    defaultValue: 0.3,
    description: "Labor cost as % of revenue (target: 25-35%)",
    min: 0,
    step: 0.01,
  },
  {
    id: "monthlyRent",
    label: "Monthly Rent",
    type: "input",
    category: "costs",
    unit: "currency",
    value: 5000,
    defaultValue: 5000,
    description: "Rent/lease payment",
    min: 0,
    step: 1,
  },
  {
    id: "monthlyUtilities",
    label: "Monthly Utilities",
    type: "input",
    category: "costs",
    unit: "currency",
    value: 1500,
    defaultValue: 1500,
    description: "Gas, electric, water",
    min: 0,
    step: 1,
  },
  {
    id: "monthlyOtherFixed",
    label: "Other Fixed Costs",
    type: "input",
    category: "costs",
    unit: "currency",
    value: 1000,
    defaultValue: 1000,
    description: "Insurance, licenses, misc",
    min: 0,
    step: 1,
  },

  // --- Computed ---
  {
    id: "dailyCovers",
    label: "Daily Covers",
    type: "computed",
    category: "operations",
    unit: "count",
    value: 0,
    defaultValue: 0,
    formula: "numberOfSeats * turnsPerDay",
    dependsOn: ["numberOfSeats", "turnsPerDay"],
    description: "Customers served per day",
  },
  {
    id: "monthlyCovers",
    label: "Monthly Covers",
    type: "computed",
    category: "operations",
    unit: "count",
    value: 0,
    defaultValue: 0,
    formula: "dailyCovers * daysOpenPerMonth",
    dependsOn: ["dailyCovers", "daysOpenPerMonth"],
    description: "Total customers per month",
  },
  {
    id: "monthlyRevenue",
    label: "Monthly Revenue",
    type: "computed",
    category: "revenue",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "monthlyCovers * averageCheck",
    dependsOn: ["monthlyCovers", "averageCheck"],
    description: "Total monthly revenue",
  },
  {
    id: "foodCost",
    label: "Monthly Food Cost",
    type: "computed",
    category: "costs",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "monthlyRevenue * foodCostPercent",
    dependsOn: ["monthlyRevenue", "foodCostPercent"],
    description: "Food & beverage costs",
  },
  {
    id: "laborCost",
    label: "Monthly Labor Cost",
    type: "computed",
    category: "costs",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "monthlyRevenue * laborCostPercent",
    dependsOn: ["monthlyRevenue", "laborCostPercent"],
    description: "Total labor costs",
  },
  {
    id: "primeCost",
    label: "Prime Cost",
    type: "computed",
    category: "costs",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "foodCost + laborCost",
    dependsOn: ["foodCost", "laborCost"],
    description: "Combined food + labor",
  },
  {
    id: "primeCostPercent",
    label: "Prime Cost %",
    type: "computed",
    category: "unitEconomics",
    unit: "percent",
    value: 0,
    defaultValue: 0,
    formula: "monthlyRevenue > 0 ? primeCost / monthlyRevenue : 0",
    dependsOn: ["primeCost", "monthlyRevenue"],
    description: "Target: 60-65%",
  },
  {
    id: "monthlyFixedCosts",
    label: "Monthly Fixed Costs",
    type: "computed",
    category: "costs",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "monthlyRent + monthlyUtilities + monthlyOtherFixed",
    dependsOn: ["monthlyRent", "monthlyUtilities", "monthlyOtherFixed"],
    description: "Total fixed overhead",
  },
  {
    id: "monthlyCosts",
    label: "Monthly Total Costs",
    type: "computed",
    category: "costs",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "primeCost + monthlyFixedCosts",
    dependsOn: ["primeCost", "monthlyFixedCosts"],
    description: "All costs combined",
  },
  {
    id: "monthlyProfit",
    label: "Monthly Profit",
    type: "computed",
    category: "unitEconomics",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "monthlyRevenue - monthlyCosts",
    dependsOn: ["monthlyRevenue", "monthlyCosts"],
    description: "Net monthly profit",
  },
  {
    id: "profitMargin",
    label: "Profit Margin",
    type: "computed",
    category: "unitEconomics",
    unit: "percent",
    value: 0,
    defaultValue: 0,
    formula: "monthlyRevenue > 0 ? monthlyProfit / monthlyRevenue : 0",
    dependsOn: ["monthlyProfit", "monthlyRevenue"],
    description: "Target: 10-15%",
  },
  {
    id: "annualRevenue",
    label: "Annual Revenue",
    type: "computed",
    category: "revenue",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "monthlyRevenue * 12",
    dependsOn: ["monthlyRevenue"],
    description: "Projected annual revenue",
  },
  {
    id: "annualProfit",
    label: "Annual Profit",
    type: "computed",
    category: "unitEconomics",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "monthlyProfit * 12",
    dependsOn: ["monthlyProfit"],
    description: "Projected annual profit",
  },
];
