import type { VariableDefinition } from "@/types/business";

export const RETAIL_VARIABLES: VariableDefinition[] = [
  // --- Revenue inputs ---
  {
    id: "monthlyFootTraffic",
    label: "Monthly Visitors",
    type: "input",
    category: "revenue",
    unit: "count",
    value: 3000,
    defaultValue: 3000,
    description: "Store visitors or website sessions per month",
    min: 0,
    step: 1,
  },
  {
    id: "conversionRate",
    label: "Conversion Rate",
    type: "input",
    category: "revenue",
    unit: "percent",
    value: 0.03,
    defaultValue: 0.03,
    description: "% of visitors who purchase",
    min: 0,
    step: 0.01,
  },
  {
    id: "averageTransactionValue",
    label: "Average Transaction Value",
    type: "input",
    category: "revenue",
    unit: "currency",
    value: 45,
    defaultValue: 45,
    description: "Average spend per purchase",
    min: 0,
    step: 1,
  },

  // --- Cost inputs ---
  {
    id: "costOfGoodsPercent",
    label: "COGS %",
    type: "input",
    category: "costs",
    unit: "percent",
    value: 0.5,
    defaultValue: 0.5,
    description: "Cost of goods as % of revenue",
    min: 0,
    step: 0.01,
  },
  {
    id: "staffCount",
    label: "Number of Staff",
    type: "input",
    category: "costs",
    unit: "count",
    value: 3,
    defaultValue: 3,
    description: "Total employees",
    min: 0,
    step: 1,
  },
  {
    id: "averageHourlyWage",
    label: "Average Hourly Wage",
    type: "input",
    category: "costs",
    unit: "currency",
    value: 15,
    defaultValue: 15,
    description: "Hourly rate per employee",
    min: 0,
    step: 1,
  },
  {
    id: "hoursPerWeek",
    label: "Hours/Week per Staff",
    type: "input",
    category: "costs",
    unit: "hours",
    value: 35,
    defaultValue: 35,
    description: "Weekly hours per employee",
    min: 0,
    step: 1,
  },
  {
    id: "monthlyRent",
    label: "Monthly Rent",
    type: "input",
    category: "costs",
    unit: "currency",
    value: 3000,
    defaultValue: 3000,
    description: "Store/warehouse rent",
    min: 0,
    step: 1,
  },
  {
    id: "monthlyMarketingBudget",
    label: "Marketing Budget",
    type: "input",
    category: "costs",
    unit: "currency",
    value: 500,
    defaultValue: 500,
    description: "Monthly marketing spend",
    min: 0,
    step: 1,
  },
  {
    id: "monthlyOtherFixed",
    label: "Other Fixed Costs",
    type: "input",
    category: "costs",
    unit: "currency",
    value: 500,
    defaultValue: 500,
    description: "Utilities, insurance, etc.",
    min: 0,
    step: 1,
  },

  // --- Computed ---
  {
    id: "monthlyTransactions",
    label: "Monthly Transactions",
    type: "computed",
    category: "revenue",
    unit: "count",
    value: 0,
    defaultValue: 0,
    formula: "monthlyFootTraffic * conversionRate",
    dependsOn: ["monthlyFootTraffic", "conversionRate"],
    description: "Number of sales per month",
  },
  {
    id: "monthlyRevenue",
    label: "Monthly Revenue",
    type: "computed",
    category: "revenue",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "monthlyTransactions * averageTransactionValue",
    dependsOn: ["monthlyTransactions", "averageTransactionValue"],
    description: "Total monthly revenue",
  },
  {
    id: "costOfGoods",
    label: "Cost of Goods Sold",
    type: "computed",
    category: "costs",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "monthlyRevenue * costOfGoodsPercent",
    dependsOn: ["monthlyRevenue", "costOfGoodsPercent"],
    description: "Monthly COGS",
  },
  {
    id: "grossProfit",
    label: "Gross Profit",
    type: "computed",
    category: "unitEconomics",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "monthlyRevenue - costOfGoods",
    dependsOn: ["monthlyRevenue", "costOfGoods"],
    description: "Revenue minus COGS",
  },
  {
    id: "monthlyLabor",
    label: "Monthly Labor Cost",
    type: "computed",
    category: "costs",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "staffCount * averageHourlyWage * hoursPerWeek * 4.33",
    dependsOn: ["staffCount", "averageHourlyWage", "hoursPerWeek"],
    description: "Total labor expense",
  },
  {
    id: "monthlyCosts",
    label: "Monthly Total Costs",
    type: "computed",
    category: "costs",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "costOfGoods + monthlyLabor + monthlyRent + monthlyMarketingBudget + monthlyOtherFixed",
    dependsOn: ["costOfGoods", "monthlyLabor", "monthlyRent", "monthlyMarketingBudget", "monthlyOtherFixed"],
    description: "All costs",
  },
  {
    id: "monthlyProfit",
    label: "Monthly Profit",
    type: "computed",
    category: "unitEconomics",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "monthlyRevenue - monthlyCosts",
    dependsOn: ["monthlyRevenue", "monthlyCosts"],
    description: "Net monthly profit",
  },
  {
    id: "profitMargin",
    label: "Profit Margin",
    type: "computed",
    category: "unitEconomics",
    unit: "percent",
    value: 0,
    defaultValue: 0,
    formula: "monthlyRevenue > 0 ? monthlyProfit / monthlyRevenue : 0",
    dependsOn: ["monthlyProfit", "monthlyRevenue"],
    description: "Profit as % of revenue",
  },
  {
    id: "grossMarginPercent",
    label: "Gross Margin %",
    type: "computed",
    category: "unitEconomics",
    unit: "percent",
    value: 0,
    defaultValue: 0,
    formula: "1 - costOfGoodsPercent",
    dependsOn: ["costOfGoodsPercent"],
    description: "Gross margin percentage",
  },
  {
    id: "annualRevenue",
    label: "Annual Revenue",
    type: "computed",
    category: "revenue",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "monthlyRevenue * 12",
    dependsOn: ["monthlyRevenue"],
    description: "Projected annual revenue",
  },
  {
    id: "annualProfit",
    label: "Annual Profit",
    type: "computed",
    category: "unitEconomics",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "monthlyProfit * 12",
    dependsOn: ["monthlyProfit"],
    description: "Projected annual profit",
  },
];
