import type { VariableDefinition } from "@/types/business";

export const SAAS_VARIABLES: VariableDefinition[] = [
  // --- Revenue inputs ---
  {
    id: "monthlyPrice",
    label: "Monthly Subscription Price",
    type: "input",
    category: "revenue",
    unit: "currency",
    value: 49,
    defaultValue: 49,
    description: "Price per customer per month",
    min: 0,
    step: 1,
  },
  {
    id: "numberOfCustomers",
    label: "Active Subscribers",
    type: "input",
    category: "revenue",
    unit: "count",
    value: 100,
    defaultValue: 100,
    description: "Current paying customers",
    min: 0,
    step: 1,
  },
  {
    id: "newCustomersPerMonth",
    label: "New Customers/Month",
    type: "input",
    category: "revenue",
    unit: "count",
    value: 20,
    defaultValue: 20,
    description: "Monthly new signups",
    min: 0,
    step: 1,
  },

  // --- Growth inputs ---
  {
    id: "monthlyChurnRate",
    label: "Monthly Churn Rate",
    type: "input",
    category: "growth",
    unit: "percent",
    value: 0.05,
    defaultValue: 0.05,
    description: "% of customers who cancel monthly",
    min: 0,
    step: 0.01,
  },
  {
    id: "customerAcquisitionCost",
    label: "Customer Acquisition Cost",
    type: "input",
    category: "growth",
    unit: "currency",
    value: 150,
    defaultValue: 150,
    description: "Cost to acquire one customer",
    min: 0,
    step: 1,
  },

  // --- Cost inputs ---
  {
    id: "grossMarginPercent",
    label: "Gross Margin",
    type: "input",
    category: "costs",
    unit: "percent",
    value: 0.8,
    defaultValue: 0.8,
    description: "Revenue margin after COGS",
    min: 0,
    step: 0.01,
  },
  {
    id: "monthlyFixedCosts",
    label: "Monthly Fixed Costs",
    type: "input",
    category: "costs",
    unit: "currency",
    value: 5000,
    defaultValue: 5000,
    description: "Overhead (rent, tools, etc.)",
    min: 0,
    step: 1,
  },

  // --- Computed ---
  {
    id: "mrr",
    label: "Monthly Recurring Revenue",
    type: "computed",
    category: "revenue",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "monthlyPrice * numberOfCustomers",
    dependsOn: ["monthlyPrice", "numberOfCustomers"],
    description: "Total monthly subscription revenue",
  },
  {
    id: "arr",
    label: "Annual Recurring Revenue",
    type: "computed",
    category: "revenue",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "mrr * 12",
    dependsOn: ["mrr"],
    description: "Annualized recurring revenue",
  },
  {
    id: "monthlyChurnedCustomers",
    label: "Churned Customers/Month",
    type: "computed",
    category: "growth",
    unit: "count",
    value: 0,
    defaultValue: 0,
    formula: "numberOfCustomers * monthlyChurnRate",
    dependsOn: ["numberOfCustomers", "monthlyChurnRate"],
    description: "Customers lost per month",
  },
  {
    id: "netNewCustomers",
    label: "Net New Customers/Month",
    type: "computed",
    category: "growth",
    unit: "count",
    value: 0,
    defaultValue: 0,
    formula: "newCustomersPerMonth - monthlyChurnedCustomers",
    dependsOn: ["newCustomersPerMonth", "monthlyChurnedCustomers"],
    description: "Growth rate in customers",
  },
  {
    id: "ltv",
    label: "Customer Lifetime Value",
    type: "computed",
    category: "unitEconomics",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "monthlyChurnRate > 0 ? monthlyPrice / monthlyChurnRate : monthlyPrice * 120",
    dependsOn: ["monthlyChurnRate", "monthlyPrice"],
    description: "Expected total revenue per customer",
  },
  {
    id: "ltvCacRatio",
    label: "LTV:CAC Ratio",
    type: "computed",
    category: "unitEconomics",
    unit: "ratio",
    value: 0,
    defaultValue: 0,
    formula: "customerAcquisitionCost > 0 ? ltv / customerAcquisitionCost : 0",
    dependsOn: ["ltv", "customerAcquisitionCost"],
    description: "Unit economics health (target: 3+)",
  },
  {
    id: "monthlyRevenue",
    label: "Monthly Revenue",
    type: "computed",
    category: "revenue",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "mrr",
    dependsOn: ["mrr"],
    description: "Total monthly revenue",
  },
  {
    id: "monthlyCOGS",
    label: "Monthly COGS",
    type: "computed",
    category: "costs",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "mrr * (1 - grossMarginPercent)",
    dependsOn: ["mrr", "grossMarginPercent"],
    description: "Cost of goods sold",
  },
  {
    id: "monthlyAcquisitionCost",
    label: "Monthly Acquisition Spend",
    type: "computed",
    category: "costs",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "newCustomersPerMonth * customerAcquisitionCost",
    dependsOn: ["newCustomersPerMonth", "customerAcquisitionCost"],
    description: "Total CAC spend",
  },
  {
    id: "monthlyCosts",
    label: "Monthly Total Costs",
    type: "computed",
    category: "costs",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "monthlyCOGS + monthlyAcquisitionCost + monthlyFixedCosts",
    dependsOn: ["monthlyCOGS", "monthlyAcquisitionCost", "monthlyFixedCosts"],
    description: "All costs combined",
  },
  {
    id: "monthlyProfit",
    label: "Monthly Profit",
    type: "computed",
    category: "unitEconomics",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "monthlyRevenue - monthlyCosts",
    dependsOn: ["monthlyRevenue", "monthlyCosts"],
    description: "Net monthly profit",
  },
  {
    id: "profitMargin",
    label: "Profit Margin",
    type: "computed",
    category: "unitEconomics",
    unit: "percent",
    value: 0,
    defaultValue: 0,
    formula: "monthlyRevenue > 0 ? monthlyProfit / monthlyRevenue : 0",
    dependsOn: ["monthlyProfit", "monthlyRevenue"],
    description: "Profit as % of revenue",
  },
  {
    id: "annualRevenue",
    label: "Annual Revenue",
    type: "computed",
    category: "revenue",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "monthlyRevenue * 12",
    dependsOn: ["monthlyRevenue"],
    description: "Projected annual revenue",
  },
  {
    id: "annualProfit",
    label: "Annual Profit",
    type: "computed",
    category: "unitEconomics",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "monthlyProfit * 12",
    dependsOn: ["monthlyProfit"],
    description: "Projected annual profit",
  },
];
