import type { VariableDefinition } from "@/types/business";

export const SERVICE_VARIABLES: VariableDefinition[] = [
  // --- Revenue inputs ---
  {
    id: "numberOfStaff",
    label: "Billable Staff",
    type: "input",
    category: "revenue",
    unit: "count",
    value: 5,
    defaultValue: 5,
    description: "Staff who bill client hours",
    min: 0,
    step: 1,
  },
  {
    id: "billableHoursPerWeek",
    label: "Billable Hours/Week",
    type: "input",
    category: "revenue",
    unit: "hours",
    value: 40,
    defaultValue: 40,
    description: "Available hours per staff per week",
    min: 0,
    step: 1,
  },
  {
    id: "utilizationRate",
    label: "Utilization Rate",
    type: "input",
    category: "revenue",
    unit: "percent",
    value: 0.75,
    defaultValue: 0.75,
    description: "% of available hours actually billed",
    min: 0,
    step: 0.01,
  },
  {
    id: "averageHourlyRate",
    label: "Average Hourly Rate",
    type: "input",
    category: "revenue",
    unit: "currency",
    value: 150,
    defaultValue: 150,
    description: "Rate charged to clients per hour",
    min: 0,
    step: 1,
  },

  // --- Cost inputs ---
  {
    id: "monthlySalaryPerStaff",
    label: "Monthly Salary/Staff",
    type: "input",
    category: "costs",
    unit: "currency",
    value: 6000,
    defaultValue: 6000,
    description: "Average monthly salary per billable employee",
    min: 0,
    step: 1,
  },
  {
    id: "monthlyOverhead",
    label: "Monthly Overhead",
    type: "input",
    category: "costs",
    unit: "currency",
    value: 3000,
    defaultValue: 3000,
    description: "Office, tools, insurance, etc.",
    min: 0,
    step: 1,
  },
  {
    id: "monthlyMarketingBudget",
    label: "Marketing Budget",
    type: "input",
    category: "costs",
    unit: "currency",
    value: 1000,
    defaultValue: 1000,
    description: "Monthly marketing spend",
    min: 0,
    step: 1,
  },

  // --- Computed ---
  {
    id: "weeklyBillableHours",
    label: "Total Billable Hours/Week",
    type: "computed",
    category: "operations",
    unit: "hours",
    value: 0,
    defaultValue: 0,
    formula: "numberOfStaff * billableHoursPerWeek * utilizationRate",
    dependsOn: ["numberOfStaff", "billableHoursPerWeek", "utilizationRate"],
    description: "Actual billable hours",
  },
  {
    id: "monthlyBillableHours",
    label: "Total Billable Hours/Month",
    type: "computed",
    category: "operations",
    unit: "hours",
    value: 0,
    defaultValue: 0,
    formula: "weeklyBillableHours * 4.33",
    dependsOn: ["weeklyBillableHours"],
    description: "Monthly billable hours",
  },
  {
    id: "monthlyRevenue",
    label: "Monthly Revenue",
    type: "computed",
    category: "revenue",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "monthlyBillableHours * averageHourlyRate",
    dependsOn: ["monthlyBillableHours", "averageHourlyRate"],
    description: "Total monthly revenue",
  },
  {
    id: "totalSalaries",
    label: "Total Monthly Salaries",
    type: "computed",
    category: "costs",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "numberOfStaff * monthlySalaryPerStaff",
    dependsOn: ["numberOfStaff", "monthlySalaryPerStaff"],
    description: "Total salary expense",
  },
  {
    id: "monthlyCosts",
    label: "Monthly Total Costs",
    type: "computed",
    category: "costs",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "totalSalaries + monthlyOverhead + monthlyMarketingBudget",
    dependsOn: ["totalSalaries", "monthlyOverhead", "monthlyMarketingBudget"],
    description: "All costs combined",
  },
  {
    id: "monthlyProfit",
    label: "Monthly Profit",
    type: "computed",
    category: "unitEconomics",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "monthlyRevenue - monthlyCosts",
    dependsOn: ["monthlyRevenue", "monthlyCosts"],
    description: "Net monthly profit",
  },
  {
    id: "profitMargin",
    label: "Profit Margin",
    type: "computed",
    category: "unitEconomics",
    unit: "percent",
    value: 0,
    defaultValue: 0,
    formula: "monthlyRevenue > 0 ? monthlyProfit / monthlyRevenue : 0",
    dependsOn: ["monthlyProfit", "monthlyRevenue"],
    description: "Profit as % of revenue",
  },
  {
    id: "revenuePerEmployee",
    label: "Revenue per Employee",
    type: "computed",
    category: "unitEconomics",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "numberOfStaff > 0 ? monthlyRevenue / numberOfStaff : 0",
    dependsOn: ["monthlyRevenue", "numberOfStaff"],
    description: "Productivity metric",
  },
  {
    id: "effectiveRate",
    label: "Effective Hourly Rate",
    type: "computed",
    category: "unitEconomics",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "monthlyBillableHours > 0 ? monthlyRevenue / (numberOfStaff * billableHoursPerWeek * 4.33) : 0",
    dependsOn: ["monthlyRevenue", "monthlyBillableHours", "numberOfStaff", "billableHoursPerWeek"],
    description: "Revenue per available hour (accounts for utilization)",
  },
  {
    id: "annualRevenue",
    label: "Annual Revenue",
    type: "computed",
    category: "revenue",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "monthlyRevenue * 12",
    dependsOn: ["monthlyRevenue"],
    description: "Projected annual revenue",
  },
  {
    id: "annualProfit",
    label: "Annual Profit",
    type: "computed",
    category: "unitEconomics",
    unit: "currency",
    value: 0,
    defaultValue: 0,
    formula: "monthlyProfit * 12",
    dependsOn: ["monthlyProfit"],
    description: "Projected annual profit",
  },
];
